### ISSUE TITLE
NEP*: Map interface wanted

### ISSUE THREAD

**Issue by tiesmaster** [nrjohnstone/kata-nethack#3]
Dear Map Subsystem designers,

We, as the Player Subsystem component guys would really like to have the following interface for the map:

``` csharp
    public interface IMap
    {
        bool CanMoveTo(int x, int y);
    }
```

Could you guys maybe implement that?

It might be the case that we need more members in it, but for now this is OK.

Thanks in a million!!

_*: NEP = Nethack Enhancement Proposal_

**Comment by d-burriss** [comment]
In design discussion we mentioned that the Player will have the x, y coordinate. So, the Map will know where the player is?

By initial design the Game engine knows the Player and the Game engine knows the Map but the Map does not know about the Player.

Thoughts?

**Comment by dburriss** [comment]
We are going to add the `IsExit(int x, int y)` to `IMap`

**Comment by heemskerkerik** [comment]
The renderer needs to be able to interrogate the map about the type of cell for each coordinate; I suggest the following:

```
interface IRenderableMap
{
    CellType GetCellType(int x, int y);
}

enum CellType
{
    Passageway,
    Wall,
    Exit
}
```

Objections?

**Comment by dburriss** [comment]
We have 

```
public enum ElementType
{
        Wall, PassageWay, Exit
}
```

**Comment by tiesmaster** [comment]
Stale
